import { Campaign, ProposedExperiment } from "./types";

export const CAMPAIGNS: Campaign[] = [
  {
    id: "dripify-danny",
    name: "Dripify — Danny",
    channel: "Dripify",
    mode: "LinkedIn",
    motion: "sales",
    status: "active",
    dateRange: "Mar 24 – present",
    targeted: 576,
    reached: 126,
    replies: 29,
    conversion: "7.5%",
    meetings: 0,
    pmfScore: 15,
    pmfNote: "Replies but no meetings. Interest is there but hasn't converted to real pipeline yet.",
    confidence: "medium",
    confidenceNote: "Accept/reply counts are tracked. Reply sentiment is not — requires manual review.",
    details: [
      { label: "Connection requests sent", value: 576 },
      { label: "Accepted", value: 126, rate: "32.6%" },
      { label: "Replies", value: 29, rate: "7.5%" },
      { label: "In progress", value: 328 },
      { label: "Finished", value: 28 },
      { label: "Paused", value: 29 },
    ],
    notes: "Demand Gen titles, NYC only. Strong accept rate at 32.6%.",
  },
  {
    id: "dripify-scott",
    name: "Dripify — Scott",
    channel: "Dripify",
    mode: "LinkedIn",
    motion: "sales",
    status: "active",
    dateRange: "Mar 29 – present",
    targeted: 230,
    reached: 27,
    replies: 2,
    conversion: "1.6%",
    meetings: 0,
    pmfScore: 5,
    pmfNote: "2 replies, no meetings. Too early to tell.",
    confidence: "medium",
    confidenceNote: "Accept/reply counts are tracked. Small sample size limits insight.",
    details: [
      { label: "Connection requests sent", value: 230 },
      { label: "Accepted", value: 27, rate: "21.3%" },
      { label: "Replies", value: 2, rate: "1.6%" },
      { label: "Finished", value: 129 },
      { label: "Remaining", value: 100 },
    ],
    notes: "Scott's connection campaign. Lower rates than Danny's — may need messaging review.",
  },
  {
    id: "dripify-kyla",
    name: "Dripify — Kyla",
    channel: "Dripify",
    mode: "LinkedIn",
    motion: "sales",
    status: "active",
    dateRange: "Mar 25 – present",
    targeted: 216,
    reached: 7,
    replies: 0,
    conversion: "0%",
    meetings: 0,
    pmfScore: 0,
    pmfNote: "Zero replies from 7 accepted connections. No PMF signal.",
    confidence: "medium",
    confidenceNote: "Tracked data but very early. 171 still in progress.",
    details: [
      { label: "Connection requests sent", value: 216 },
      { label: "Accepted", value: 7, rate: "15.6%" },
      { label: "Replies", value: 0, rate: "0%" },
      { label: "In progress", value: 171 },
      { label: "Finished", value: 45 },
    ],
    notes: "VPs of Demand Gen. Low accept rate, zero replies. Early but concerning.",
  },
  {
    id: "lemlist-danny",
    name: "Lemlist — AccountCast (Danny)",
    channel: "Lemlist",
    mode: "Email",
    motion: "sales",
    status: "active",
    dateRange: "Mar 2026 – present",
    targeted: 147,
    reached: 0,
    replies: 0,
    conversion: "0%",
    meetings: 0,
    pmfScore: 0,
    pmfNote: "147 emails sent, 0 opened, 0 replies. No engagement at all — deliverability issue or wrong audience.",
    confidence: "high",
    confidenceNote: "Data from Lemlist API. 3 bounced.",
    details: [
      { label: "Emails sent", value: 147 },
      { label: "Opened", value: 0, rate: "0%" },
      { label: "Replied", value: 0, rate: "0%" },
      { label: "Bounced", value: 3 },
      { label: "Audience", value: "Enrich TAL + Intent — Tier 2" },
    ],
    notes: "Zero opens is a red flag — emails may be going to spam or the subject line isn't landing.",
  },
  {
    id: "lemlist-kyla",
    name: "Lemlist — Tier 1 AccountCast (Kyla)",
    channel: "Lemlist",
    mode: "Email",
    motion: "sales",
    status: "active",
    dateRange: "Mar 2026 – present",
    targeted: 35,
    reached: 22,
    replies: 2,
    conversion: "9%",
    meetings: 0,
    pmfScore: 9,
    pmfNote: "2 replies from 22 who opened (9%). Opens are strong at 63% but replies not converting to meetings.",
    confidence: "high",
    confidenceNote: "Sent/opened from Lemlist API. Replies reported manually (API shows 0 — may be tracked outside Lemlist).",
    details: [
      { label: "Emails sent", value: 35 },
      { label: "Opened", value: 22, rate: "63%" },
      { label: "Replied", value: 2, rate: "9% of opens" },
      { label: "Bounced", value: 1 },
      { label: "Audience", value: "Enrich TAL + Intent — Tier 1" },
    ],
    notes: "63% open rate is strong. 2 replies but not tracked in Lemlist — may have replied directly. Tier 1 audience is more responsive than Tier 2.",
  },
  {
    id: "lemlist-scott-interview",
    name: "Lemlist — Scott's Customer Interview Push",
    channel: "Lemlist",
    mode: "Email",
    motion: "sales",
    status: "active",
    dateRange: "Mar 25 – Apr 9, 2026",
    targeted: 415,
    reached: 86,
    replies: 3,
    conversion: "3.4%",
    meetings: 0,
    pmfScore: 5,
    pmfNote: "3 answers from 86 reached (3.4%). Low reply rate but campaign is still running with 415 leads loaded.",
    confidence: "high",
    confidenceNote: "Data from Lemlist UI (API was degraded). 86 sent, 100% delivered.",
    details: [
      { label: "Leads in campaign", value: 415 },
      { label: "Leads launched", value: 89, rate: "21.4%" },
      { label: "Leads reached", value: 86, rate: "20.7%" },
      { label: "Messages sent", value: 86 },
      { label: "Delivered", value: 86, rate: "100%" },
      { label: "Opened", value: 16, rate: "18%" },
      { label: "Answered", value: 3, rate: "3.4%" },
      { label: "Interested", value: 0 },
    ],
    notes: "415 leads loaded, only 89 launched so far. 18% open rate, 3.4% answer rate. Still ramping up.",
  },
  {
    id: "lemlist-launch",
    name: "Lemlist — AccountCast Launch",
    channel: "Lemlist",
    mode: "Email",
    motion: "sales",
    status: "active",
    dateRange: "2026",
    targeted: 24,
    reached: 59,
    replies: 13,
    conversion: "54%",
    meetings: 0,
    pmfScore: 20,
    pmfNote: "13 replies from ~24 sent (54% reply rate). Strong engagement but campaign status shows ended.",
    confidence: "high",
    confidenceNote: "Data from Lemlist API activities. High reply rate.",
    details: [
      { label: "Emails sent", value: 24 },
      { label: "Opens (total, incl. re-opens)", value: 59 },
      { label: "Replied", value: 13 },
      { label: "Bounced", value: 2 },
    ],
    notes: "54% reply rate is very high — this audience is engaged. Opens > sends means multiple opens per person.",
  },
  {
    id: "ctv",
    name: "CTV Ads — AccountCast TAL",
    channel: "Trade Desk / Bombora",
    mode: "CTV",
    motion: "marketing",
    status: "active",
    dateRange: "Mar 2026 – present",
    targeted: 47606,
    reached: 550,
    replies: "n/a",
    conversion: "0%",
    meetings: 0,
    pmfScore: null,
    pmfNote: "Can't measure PMF directly from CTV. 550 accounts reached with 97% video completion — engagement is high but no way to track if it drives meetings yet.",
    confidence: "high",
    confidenceNote: "Data from Bombora B2beacon / Trade Desk dashboard. Fully tracked.",
    details: [
      { label: "Impressions", value: "47,606" },
      { label: "Accounts reached", value: 550 },
      { label: "Devices", value: "40,291" },
      { label: "Clicks", value: 0, rate: "0.00% CTR" },
      { label: "Video starts", value: "47,599" },
      { label: "Video completes", value: "46,031", rate: "96.71%" },
      { label: "Total media cost", value: "$887.35" },
      { label: "Audience", value: "TIMA_AccountCast_Clay Domains" },
    ],
    notes: "97% video completion is excellent — people are watching the full ad. But 0 clicks means the CTA in the ad isn't driving action, or CTV viewers don't click (expected for TV). Need to measure lift via website visits and brand recall instead.",
  },
  {
    id: "linkedin-ads",
    name: "LinkedIn Ads",
    channel: "LinkedIn",
    mode: "Paid",
    motion: "marketing",
    status: "planned",
    dateRange: "Not started",
    targeted: null,
    reached: null,
    replies: "n/a",
    conversion: null,
    meetings: 0,
    pmfScore: 0,
    pmfNote: "Not started yet. No data to measure.",
    confidence: "low",
    confidenceNote: "Campaign has not launched.",
    details: [],
    notes: "Planned LinkedIn ads campaign. Not yet active.",
  },
  {
    id: "homepage",
    name: "Homepage",
    channel: "accountcast.tv",
    mode: "",
    motion: "product",
    status: "active",
    dateRange: "Feb 2026 – present",
    targeted: "n/a",
    reached: 541,
    replies: "n/a",
    conversion: "0%",
    meetings: 0,
    pmfScore: 0,
    pmfNote: "541 visitors, zero CTA clicks. The 'at last' message may be landing but 'Talk to Sales' is not converting.",
    confidence: "high",
    confidenceNote: "Vercel analytics — fully tracked page views, visitors, and CTA clicks.",
    details: [
      { label: "Page views", value: 811 },
      { label: "Unique visitors", value: 541 },
      { label: "Bounce rate", value: "72%" },
      { label: "CTA clicks", value: 0, rate: "0%" },
      { label: "Top referrer", value: "imasdk.googleapis.com (50)" },
      { label: "Google", value: 22 },
      { label: "LinkedIn", value: 7 },
      { label: "Geography", value: "77% US" },
      { label: "Device", value: "80% desktop" },
    ],
    notes: "Traffic growing (+464%) but zero conversions. 'Talk to Sales' CTA needs to change.",
  },
  {
    id: "scott-blast-1",
    name: "Scott — TIMA Clients #1",
    channel: "Email",
    mode: "Direct",
    motion: "sales",
    status: "active",
    dateRange: "Mar 2026",
    targeted: 250,
    reached: 150,
    replies: null,
    conversion: "0.4%",
    meetings: 1,
    pmfScore: 30,
    pmfNote: "1 qualified opp (Adelaide) from 250 emails. Low conversion rate but the opp that came through is real and in pipeline.",
    confidence: "medium",
    confidenceNote: "Email count and open rate are approximate. Adelaide opp is confirmed in Pipedrive.",
    details: [
      { label: "Emails sent", value: 250 },
      { label: "Opened", value: "~150", rate: "~60%" },
      { label: "Opps generated", value: 1 },
      { label: "Deal from campaign", value: "Adelaide" },
    ],
    notes: "Only Adelaide came from this campaign. Other pipeline deals (WEKA, Guardian Life, Consumable) came from organic/relationships. Instructure is an existing TIMA client.",
  },
  {
    id: "scott-blast-2",
    name: "Scott — TIMA Clients #2",
    channel: "Email",
    mode: "Direct",
    motion: "sales",
    status: "active",
    dateRange: "Mar 2026",
    targeted: 100,
    reached: null,
    replies: 0,
    conversion: "0%",
    meetings: 0,
    pmfScore: 0,
    pmfNote: "Second blast to same audience. Zero replies — message fatigue or wrong CTA.",
    confidence: "medium",
    confidenceNote: "Send count is known. Open/reply data approximate.",
    details: [
      { label: "Emails sent", value: 100 },
      { label: "Audience", value: "Same as Blast #1" },
      { label: "Replies", value: 0, rate: "0%" },
    ],
    notes: "Re-blast to same 100 people from Blast #1. Zero engagement — diminishing returns on same audience.",
  },
];

export const PROPOSED_EXPERIMENTS: ProposedExperiment[] = [
  {
    id: "prop-001",
    name: "Free Target Account List Offer",
    channel: "Lemlist",
    motion: "sales",
    hypothesis:
      "Offering a free TAL with intent data as a lead magnet will be more compelling than asking for a meeting — lower commitment, immediate value.",
    ctaTested: "Free Target Account List with intent data",
    durationWeeks: 2,
    successCriteria:
      "15%+ reply rate on Lemlist (vs. current 0%) and 50%+ of TAL recipients request a follow-up call.",
    defaultScore: 5,
    startDate: "",
  },
  {
    id: "prop-003a",
    name: "Homepage CTA — 60s Demo Video",
    channel: "accountcast.tv",
    motion: "product",
    hypothesis:
      "Replacing 'Talk to Sales' with 'See a 60-second demo' removes all commitment. Prospects can experience the magic moment without talking to anyone.",
    ctaTested: "See a 60-second demo",
    durationWeeks: 2,
    successCriteria:
      "1%+ CTA click rate (vs. current 0%). 50%+ video completion.",
    defaultScore: 0,
    startDate: "",
  },
  {
    id: "prop-003b",
    name: "Homepage CTA — Free TAL Builder",
    channel: "accountcast.tv",
    motion: "product",
    hypothesis:
      "Offering a free Target Account List gives immediate value. Prospects see their accounts with intent data and realize the product is real.",
    ctaTested: "Build your free Target Account List",
    durationWeeks: 2,
    successCriteria:
      "1%+ CTA click rate. 10+ TALs built in first 2 weeks.",
    defaultScore: 0,
    startDate: "",
  },
  {
    id: "prop-003c",
    name: "Homepage CTA — $2K Credit",
    channel: "accountcast.tv",
    motion: "product",
    hypothesis:
      "A $2,000 campaign credit reduces perceived risk. Prospects feel like they're getting something instead of being sold to.",
    ctaTested: "Get $2,000 towards your first campaign",
    durationWeeks: 4,
    successCriteria:
      "1%+ CTA click rate (vs. current 0%).",
    defaultScore: 0,
    startDate: "",
  },
  {
    id: "prop-003d",
    name: "Homepage CTA — In-Market Accounts",
    channel: "accountcast.tv",
    motion: "product",
    hypothesis:
      "Curiosity-driven CTA using intent data. 'Which of your accounts are in-market right now?' is hard to ignore for any Demand Gen leader.",
    ctaTested: "See which of your accounts are in-market",
    durationWeeks: 2,
    successCriteria:
      "1%+ CTA click rate. Higher engagement time on page.",
    defaultScore: 0,
    startDate: "",
  },
  {
    id: "prop-003e",
    name: "Homepage CTA — Free CTV Audit",
    channel: "accountcast.tv",
    motion: "product",
    hypothesis:
      "For brands already running CTV, a free audit positions AccountCast as the expert and shows gaps in their current B2B targeting.",
    ctaTested: "Get a free CTV creative audit",
    durationWeeks: 2,
    successCriteria:
      "1%+ CTA click rate. 3+ audits requested in 2 weeks.",
    defaultScore: 0,
    startDate: "",
  },
  {
    id: "prop-002",
    name: "CTV Creative Audit Offer",
    channel: "Lemlist",
    motion: "sales",
    hypothesis:
      "Brands already running CTV will engage with a free audit that shows gaps in their B2B targeting — positions AccountCast as the expert.",
    ctaTested: "Free CTV creative audit",
    durationWeeks: 2,
    successCriteria:
      "10%+ reply rate and 3+ audits delivered in 2 weeks.",
    defaultScore: 3,
    startDate: "",
  },
  {
    id: "prop-005",
    name: "Multithread — Dripify + Lemlist",
    channel: "Dripify + Lemlist",
    motion: "sales",
    hypothesis:
      "Reaching the same prospects on both LinkedIn and email will increase reply rates vs. single-channel outreach.",
    ctaTested: "Schedule a meeting",
    durationWeeks: 3,
    successCriteria:
      "Combined reply rate 15%+ (vs. ~7% LinkedIn-only and 0% email-only).",
    defaultScore: 2,
    startDate: "",
  },
  {
    id: "prop-004",
    name: "LinkedIn Ads — Awareness Campaign",
    channel: "LinkedIn",
    motion: "marketing",
    hypothesis:
      "Targeted LinkedIn ads to VP/Director Demand Gen will drive awareness and website visits, complementing the outbound motion.",
    ctaTested: "Schedule a demo",
    durationWeeks: 4,
    successCriteria:
      "CTR above 0.5%, at least 50 website visits from ads, 1+ demo request.",
    defaultScore: 1,
    startDate: "",
  },
  {
    id: "prop-006",
    name: "Loom Video Outbound",
    channel: "Lemlist",
    motion: "sales",
    hypothesis:
      "Personalized 60-second Loom videos showing what a CTV campaign would look like for the prospect's accounts will deliver the 'at last' moment visually — the way Scott does it 1:1.",
    ctaTested: "Schedule a demo",
    durationWeeks: 2,
    successCriteria:
      "20%+ video view rate, 10%+ reply rate, 1+ meeting booked.",
    defaultScore: 0,
    startDate: "",
  },
  {
    id: "prop-007",
    name: "Free Pilot — 'We Already Ran It'",
    channel: "Email",
    motion: "sales",
    hypothesis:
      "Run a tiny CTV campaign (1K impressions) against a prospect's target accounts without asking, then send results. Removes all friction — proves the product before they talk to us.",
    ctaTested: "See your campaign results",
    durationWeeks: 3,
    successCriteria:
      "3+ pilots delivered, 50%+ of pilot recipients take a follow-up call.",
    defaultScore: 0,
    startDate: "",
  },
  {
    id: "prop-008",
    name: "Homepage Video — 60 Second Demo",
    channel: "accountcast.tv",
    motion: "product",
    hypothesis:
      "Replace the text-heavy homepage with a 60-second video walkthrough of a real campaign. Let prospects SEE the magic moment instead of reading about it.",
    ctaTested: "Start your free campaign",
    durationWeeks: 2,
    successCriteria:
      "1%+ CTA click rate (vs. current 0%). 50%+ video completion rate.",
    defaultScore: 0,
    startDate: "",
  },
  {
    id: "prop-009",
    name: "Live 'B2B CTV in Action' Webinar",
    channel: "Events / Zoom",
    motion: "sales",
    hypothesis:
      "Scott's 1:1 pitch converts 100%. A monthly live demo webinar scales that to 1:many — invite the entire Dripify/Lemlist list to see it live.",
    ctaTested: "Register for live demo",
    durationWeeks: 4,
    successCriteria:
      "20+ registrations, 50%+ attendance, 3+ follow-up meetings from attendees.",
    defaultScore: 0,
    startDate: "",
  },
  {
    id: "prop-010",
    name: "Self-Serve Audience Builder",
    channel: "accountcast.tv",
    motion: "product",
    hypothesis:
      "Let anyone build a free Target Account List with intent data on the website — no login. They see the power of the data, then we ask for the meeting.",
    ctaTested: "Build your free TAL",
    durationWeeks: 4,
    successCriteria:
      "50+ TALs built in first month, 10%+ of builders request a follow-up.",
    defaultScore: 0,
    startDate: "",
  },
  {
    id: "prop-011",
    name: "Agency Partner Play",
    channel: "Partnerships",
    motion: "sales",
    hypothesis:
      "Find 3-5 media agencies already selling to Demand Gen leaders. Give them a white-label pitch and rev share. They have the trust, we have the product.",
    ctaTested: "Partner referral",
    durationWeeks: 4,
    successCriteria:
      "3+ agency partners signed, 1+ deal sourced through a partner in 60 days.",
    defaultScore: 0,
    startDate: "",
  },
];
