import { Campaign, ProposedExperiment } from "./types";

export const CAMPAIGNS: Campaign[] = [
  {
    id: "dripify-danny",
    name: "Dripify — Danny",
    channel: "Dripify",
    mode: "LinkedIn",
    motion: "sales",
    status: "active",
    dateRange: "Mar 24 – present",
    targeted: 576,
    reached: 126,
    replies: 29,
    conversion: "7.5%",
    meetings: 0,
    pmfScore: 15,
    pmfNote: "Replies but no meetings. Interest is there but hasn't converted to real pipeline yet.",
    confidence: "medium",
    confidenceNote: "Accept/reply counts are tracked. Reply sentiment is not — requires manual review.",
    details: [
      { label: "Connection requests sent", value: 576 },
      { label: "Accepted", value: 126, rate: "32.6%" },
      { label: "Replies", value: 29, rate: "7.5%" },
      { label: "In progress", value: 328 },
      { label: "Finished", value: 28 },
      { label: "Paused", value: 29 },
    ],
    notes: "Demand Gen titles, NYC only. Strong accept rate at 32.6%.",
  },
  {
    id: "dripify-scott",
    name: "Dripify — Scott",
    channel: "Dripify",
    mode: "LinkedIn",
    motion: "sales",
    status: "active",
    dateRange: "Mar 29 – present",
    targeted: 230,
    reached: 27,
    replies: 2,
    conversion: "1.6%",
    meetings: 0,
    pmfScore: 5,
    pmfNote: "2 replies, no meetings. Too early to tell.",
    confidence: "medium",
    confidenceNote: "Accept/reply counts are tracked. Small sample size limits insight.",
    details: [
      { label: "Connection requests sent", value: 230 },
      { label: "Accepted", value: 27, rate: "21.3%" },
      { label: "Replies", value: 2, rate: "1.6%" },
      { label: "Finished", value: 129 },
      { label: "Remaining", value: 100 },
    ],
    notes: "Scott's connection campaign. Lower rates than Danny's — may need messaging review.",
  },
  {
    id: "dripify-kyla",
    name: "Dripify — Kyla",
    channel: "Dripify",
    mode: "LinkedIn",
    motion: "sales",
    status: "active",
    dateRange: "Mar 25 – present",
    targeted: 216,
    reached: 7,
    replies: 0,
    conversion: "0%",
    meetings: 0,
    pmfScore: 0,
    pmfNote: "Zero replies from 7 accepted connections. No PMF signal.",
    confidence: "medium",
    confidenceNote: "Tracked data but very early. 171 still in progress.",
    details: [
      { label: "Connection requests sent", value: 216 },
      { label: "Accepted", value: 7, rate: "15.6%" },
      { label: "Replies", value: 0, rate: "0%" },
      { label: "In progress", value: 171 },
      { label: "Finished", value: 45 },
    ],
    notes: "VPs of Demand Gen. Low accept rate, zero replies. Early but concerning.",
  },
  {
    id: "lemlist-danny",
    name: "Lemlist — Danny",
    channel: "Lemlist",
    mode: "Email",
    motion: "sales",
    status: "active",
    dateRange: "Mar 2026 – present",
    targeted: 80,
    reached: null,
    replies: 0,
    conversion: "0%",
    meetings: 0,
    pmfScore: 0,
    pmfNote: "80 emails sent, zero replies. No PMF signal from this audience.",
    confidence: "medium",
    confidenceNote: "Send/reply counts known. Open rate will come from API when Lemlist recovers.",
    details: [
      { label: "Emails sent", value: 80 },
      { label: "Opened", value: "Pending API" },
      { label: "Replies", value: 0, rate: "0%" },
      { label: "Audience", value: "Enrich TAL + Intent — Tier 2" },
    ],
    notes: "Enrich TAL + Intent, Tier 2. Zero replies — this audience isn't responding to email.",
  },
  {
    id: "lemlist-kyla",
    name: "Lemlist — Kyla",
    channel: "Lemlist",
    mode: "Email",
    motion: "sales",
    status: "active",
    dateRange: "Mar 2026 – present",
    targeted: 40,
    reached: null,
    replies: 0,
    conversion: "0%",
    meetings: 0,
    pmfScore: 0,
    pmfNote: "40 emails sent, zero replies. No PMF signal.",
    confidence: "medium",
    confidenceNote: "Send/reply counts known. Open rate will come from API when Lemlist recovers.",
    details: [
      { label: "Emails sent", value: 40 },
      { label: "Opened", value: "Pending API" },
      { label: "Replies", value: 0, rate: "0%" },
      { label: "Audience", value: "Enrich TAL + Intent — Tier 1" },
    ],
    notes: "Enrich TAL + Intent, Tier 1. Zero replies.",
  },
  {
    id: "ctv",
    name: "CTV Ads",
    channel: "CTV",
    mode: "",
    motion: "marketing",
    status: "active",
    dateRange: "Mar 2026 – present",
    targeted: null,
    reached: null,
    replies: "n/a",
    conversion: null,
    meetings: 0,
    pmfScore: 0,
    pmfNote: "No performance data yet. Cannot measure PMF without impression and conversion data.",
    confidence: "low",
    confidenceNote: "No data available yet. Waiting on campaign reporting.",
    details: [],
    notes: "CTV campaign running. Awaiting performance data.",
  },
  {
    id: "linkedin-ads",
    name: "LinkedIn Ads",
    channel: "LinkedIn",
    mode: "Paid",
    motion: "marketing",
    status: "planned",
    dateRange: "Not started",
    targeted: null,
    reached: null,
    replies: "n/a",
    conversion: null,
    meetings: 0,
    pmfScore: 0,
    pmfNote: "Not started yet. No data to measure.",
    confidence: "low",
    confidenceNote: "Campaign has not launched.",
    details: [],
    notes: "Planned LinkedIn ads campaign. Not yet active.",
  },
  {
    id: "homepage",
    name: "Homepage",
    channel: "accountcast.tv",
    mode: "",
    motion: "product",
    status: "active",
    dateRange: "Feb 2026 – present",
    targeted: "n/a",
    reached: 541,
    replies: "n/a",
    conversion: "0%",
    meetings: 0,
    pmfScore: 0,
    pmfNote: "541 visitors, zero CTA clicks. The 'at last' message may be landing but 'Talk to Sales' is not converting.",
    confidence: "high",
    confidenceNote: "Vercel analytics — fully tracked page views, visitors, and CTA clicks.",
    details: [
      { label: "Page views", value: 811 },
      { label: "Unique visitors", value: 541 },
      { label: "Bounce rate", value: "72%" },
      { label: "CTA clicks", value: 0, rate: "0%" },
      { label: "Top referrer", value: "imasdk.googleapis.com (50)" },
      { label: "Google", value: 22 },
      { label: "LinkedIn", value: 7 },
      { label: "Geography", value: "77% US" },
      { label: "Device", value: "80% desktop" },
    ],
    notes: "Traffic growing (+464%) but zero conversions. 'Talk to Sales' CTA needs to change.",
  },
  {
    id: "founder",
    name: "Founder-Led Sales",
    channel: "Scott direct",
    mode: "Email",
    motion: "sales",
    status: "active",
    dateRange: "Mar 2026 – present",
    targeted: 200,
    reached: 200,
    replies: 30,
    conversion: "15%",
    meetings: 4,
    pmfScore: 75,
    pmfNote: "4 meetings, all became qualified leads. Deals in progress. Strongest PMF signal — close to 80% target if a deal closes.",
    confidence: "low",
    confidenceNote: "Numbers are estimated by Danny — not from a tracked system. Small sample, warm network.",
    details: [
      { label: "Emails sent (estimated)", value: 200 },
      { label: "Replies (estimated)", value: 30, rate: "~15%" },
      { label: "Meetings booked", value: 4 },
      { label: "Qualified leads", value: 4, rate: "100%" },
      { label: "Source", value: "TIMA community" },
    ],
    notes: "Strongest PMF signal but smallest sample. Warm network. Numbers are estimates, not tracked.",
  },
];

export const PROPOSED_EXPERIMENTS: ProposedExperiment[] = [
  {
    id: "prop-001",
    name: "Free Target Account List Offer",
    channel: "Lemlist",
    motion: "sales",
    hypothesis:
      "Offering a free TAL with intent data as a lead magnet will be more compelling than asking for a meeting — lower commitment, immediate value.",
    ctaTested: "Free Target Account List with intent data",
    durationWeeks: 2,
    successCriteria:
      "15%+ reply rate on Lemlist (vs. current 0%) and 50%+ of TAL recipients request a follow-up call.",
  },
  {
    id: "prop-002",
    name: "CTV Creative Audit Offer",
    channel: "Lemlist",
    motion: "sales",
    hypothesis:
      "Brands already running CTV will engage with a free audit that shows gaps in their B2B targeting — positions AccountCast as the expert.",
    ctaTested: "Free CTV creative audit",
    durationWeeks: 2,
    successCriteria:
      "10%+ reply rate and 3+ audits delivered in 2 weeks.",
  },
  {
    id: "prop-003",
    name: "Homepage CTA Split Test",
    channel: "accountcast.tv",
    motion: "product",
    hypothesis:
      "Replacing 'Talk to Sales' with '$2,000 credit towards your first campaign' will convert more visitors because it reduces perceived risk.",
    ctaTested: "$2,000 credit towards your first qualified campaign",
    durationWeeks: 4,
    successCriteria:
      "At least 1 CTA click per 100 visitors (1% CTR) — vs. current 0%.",
  },
  {
    id: "prop-004",
    name: "LinkedIn Ads — Awareness Campaign",
    channel: "LinkedIn",
    motion: "marketing",
    hypothesis:
      "Targeted LinkedIn ads to VP/Director Demand Gen will drive awareness and website visits, complementing the outbound motion.",
    ctaTested: "Schedule a demo",
    durationWeeks: 4,
    successCriteria:
      "CTR above 0.5%, at least 50 website visits from ads, 1+ demo request.",
  },
  {
    id: "prop-005",
    name: "Multithread — Dripify + Lemlist",
    channel: "Dripify + Lemlist",
    motion: "sales",
    hypothesis:
      "Reaching the same prospects on both LinkedIn and email will increase reply rates vs. single-channel outreach.",
    ctaTested: "Schedule a meeting",
    durationWeeks: 3,
    successCriteria:
      "Combined reply rate 15%+ (vs. ~7% LinkedIn-only and 0% email-only).",
  },
];
