import { Campaign, ProposedExperiment } from "./types";

export const CAMPAIGNS: Campaign[] = [
  {
    id: "dripify-danny",
    name: "Dripify — Danny",
    channel: "Dripify",
    mode: "LinkedIn",
    motion: "sales",
    status: "active",
    dateRange: "Mar 24 – present",
    startDate: "2026-03-24",
    targeted: 576,
    reached: 126,
    replies: 29,
    conversion: "7.5%",
    meetings: 0,
    pmfScore: 15,
    pmfNote: "Replies but no meetings. Interest is there but hasn't converted to real pipeline yet.",
    confidence: "medium",
    confidenceNote: "Accept/reply counts are tracked. Reply sentiment is not — requires manual review.",
    details: [
      { label: "Connection requests sent", value: 576 },
      { label: "Accepted", value: 126, rate: "32.6%" },
      { label: "Replies", value: 29, rate: "7.5%" },
      { label: "In progress", value: 328 },
      { label: "Finished", value: 28 },
      { label: "Paused", value: 29 },
    ],
    notes: "Demand Gen titles, NYC only. Strong accept rate at 32.6%.",
  },
  {
    id: "dripify-scott",
    name: "Dripify — Scott",
    channel: "Dripify",
    mode: "LinkedIn",
    motion: "sales",
    status: "active",
    dateRange: "Mar 29 – present",
    startDate: "2026-03-29",
    targeted: 230,
    reached: 27,
    replies: 2,
    conversion: "1.6%",
    meetings: 0,
    pmfScore: 5,
    pmfNote: "2 replies, no meetings. Too early to tell.",
    confidence: "medium",
    confidenceNote: "Accept/reply counts are tracked. Small sample size limits insight.",
    details: [
      { label: "Connection requests sent", value: 230 },
      { label: "Accepted", value: 27, rate: "21.3%" },
      { label: "Replies", value: 2, rate: "1.6%" },
      { label: "Finished", value: 129 },
      { label: "Remaining", value: 100 },
    ],
    notes: "Scott's connection campaign. Lower rates than Danny's — may need messaging review.",
  },
  {
    id: "dripify-kyla",
    name: "Dripify — Kyla",
    channel: "Dripify",
    mode: "LinkedIn",
    motion: "sales",
    status: "active",
    dateRange: "Mar 25 – present",
    startDate: "2026-03-25",
    targeted: 216,
    reached: 7,
    replies: 0,
    conversion: "0%",
    meetings: 0,
    pmfScore: 0,
    pmfNote: "Zero replies from 7 accepted connections. No PMF signal.",
    confidence: "medium",
    confidenceNote: "Tracked data but very early. 171 still in progress.",
    details: [
      { label: "Connection requests sent", value: 216 },
      { label: "Accepted", value: 7, rate: "15.6%" },
      { label: "Replies", value: 0, rate: "0%" },
      { label: "In progress", value: 171 },
      { label: "Finished", value: 45 },
    ],
    notes: "VPs of Demand Gen. Low accept rate, zero replies. Early but concerning.",
  },
  {
    id: "lemlist-danny",
    name: "Lemlist — AccountCast (Danny)",
    channel: "Lemlist",
    mode: "Email",
    motion: "sales",
    status: "active",
    dateRange: "Mar 2026 – present",
    targeted: 178,
    reached: 0,
    replies: 0,
    conversion: "0%",
    meetings: 0,
    pmfScore: 0,
    pmfNote: "178 emails sent, 0 opened, 0 replies. Deliverability issue — emails likely going to spam.",
    confidence: "high",
    confidenceNote: "Data from Lemlist API (Apr 14).",
    details: [
      { label: "Emails sent", value: 178 },
      { label: "Opened", value: 0, rate: "0%" },
      { label: "Replied", value: 0, rate: "0%" },
      { label: "Audience", value: "Enrich TAL + Intent — Tier 2" },
    ],
    notes: "178 emails, zero opens. Deliverability issue persists.",
  },
  {
    id: "lemlist-kyla",
    name: "Lemlist — Tier 1 AccountCast (Kyla)",
    channel: "Lemlist",
    mode: "Email",
    motion: "sales",
    status: "active",
    dateRange: "Mar 2026 – present",
    targeted: 65,
    reached: 42,
    replies: 0,
    conversion: "0%",
    meetings: 0,
    pmfScore: 5,
    pmfNote: "65 sent, 42 opened (65% open rate) but 0 replies in API. Strong opens, no conversions yet.",
    confidence: "high",
    confidenceNote: "Data from Lemlist API (Apr 14).",
    details: [
      { label: "Emails sent", value: 65 },
      { label: "Opened", value: 42, rate: "65%" },
      { label: "Replied", value: 0, rate: "0%" },
      { label: "Audience", value: "Enrich TAL + Intent — Tier 1" },
    ],
    notes: "63% open rate is strong. 2 replies but not tracked in Lemlist — may have replied directly. Tier 1 audience is more responsive than Tier 2.",
  },
  {
    id: "lemlist-scott-interview",
    name: "Lemlist — Scott's Customer Interview Push",
    channel: "Lemlist",
    mode: "Email",
    motion: "sales",
    status: "active",
    dateRange: "Mar 25 – Apr 9, 2026",
    startDate: "2026-03-25",
    targeted: 87,
    reached: 35,
    replies: 12,
    conversion: "14%",
    meetings: 0,
    pmfScore: 20,
    pmfNote: "12 replies from 87 sent (14% reply rate). Best performing email campaign. 35 opened (40%).",
    confidence: "high",
    confidenceNote: "Data from Lemlist API (Apr 14).",
    details: [
      { label: "Emails sent", value: 87 },
      { label: "Opened", value: 35, rate: "40%" },
      { label: "Replied", value: 12, rate: "14%" },
    ],
    notes: "14% reply rate — strongest email campaign. Scott's personal network driving engagement.",
  },
  {
    id: "lemlist-launch",
    name: "Lemlist — AccountCast Launch",
    channel: "Lemlist",
    mode: "Email",
    motion: "sales",
    status: "active",
    dateRange: "2026",
    targeted: 432,
    reached: 327,
    replies: 33,
    conversion: "7.6%",
    meetings: 0,
    pmfScore: 15,
    pmfNote: "33 replies from 432 sent (7.6%). 327 opened (76% open rate). Large campaign with decent engagement.",
    confidence: "high",
    confidenceNote: "Data from Lemlist API (Apr 14).",
    details: [
      { label: "Emails sent", value: 432 },
      { label: "Opened", value: 327, rate: "76%" },
      { label: "Replied", value: 33, rate: "7.6%" },
    ],
    notes: "76% open rate is excellent. 33 replies — largest volume campaign.",
  },
  {
    id: "ctv",
    name: "CTV Ads — AccountCast TAL",
    channel: "Trade Desk / Bombora",
    mode: "CTV",
    motion: "marketing",
    status: "active",
    dateRange: "Mar 2026 – present",
    startDate: "2026-03-01",
    targeted: 47606,
    reached: 550,
    replies: "n/a",
    conversion: "0%",
    meetings: 0,
    pmfScore: null,
    pmfNote: "Can't measure PMF directly from CTV. 550 accounts reached with 97% video completion — engagement is high but no way to track if it drives meetings yet.",
    confidence: "high",
    confidenceNote: "Data from Bombora B2beacon / Trade Desk dashboard. Fully tracked.",
    details: [
      { label: "Impressions", value: "47,606" },
      { label: "Accounts reached", value: 550 },
      { label: "Devices", value: "40,291" },
      { label: "Clicks", value: 0, rate: "0.00% CTR" },
      { label: "Video starts", value: "47,599" },
      { label: "Video completes", value: "46,031", rate: "96.71%" },
      { label: "Total media cost", value: "$887.35" },
      { label: "Audience", value: "TIMA_AccountCast_Clay Domains" },
    ],
    notes: "97% video completion is excellent — people are watching the full ad. But 0 clicks means the CTA in the ad isn't driving action, or CTV viewers don't click (expected for TV). Need to measure lift via website visits and brand recall instead.",
  },
  {
    id: "linkedin-ads",
    name: "LinkedIn Ads",
    channel: "LinkedIn",
    mode: "Paid",
    motion: "marketing",
    status: "planned",
    dateRange: "Not started",
    targeted: null,
    reached: null,
    replies: "n/a",
    conversion: null,
    meetings: 0,
    pmfScore: 0,
    pmfNote: "Not started yet. No data to measure.",
    confidence: "low",
    confidenceNote: "Campaign has not launched.",
    details: [],
    notes: "Planned LinkedIn ads campaign. Not yet active.",
  },
  {
    id: "homepage",
    name: "Homepage",
    channel: "accountcast.tv",
    mode: "",
    motion: "product",
    status: "active",
    dateRange: "Feb 2026 – present",
    startDate: "2026-02-01",
    targeted: "n/a",
    reached: 541,
    replies: "n/a",
    conversion: "0%",
    meetings: 0,
    pmfScore: 0,
    pmfNote: "541 visitors, zero CTA clicks. The 'at last' message may be landing but 'Talk to Sales' is not converting.",
    confidence: "high",
    confidenceNote: "Vercel analytics — fully tracked page views, visitors, and CTA clicks.",
    details: [
      { label: "Page views", value: 811 },
      { label: "Unique visitors", value: 541 },
      { label: "Bounce rate", value: "72%" },
      { label: "CTA clicks", value: 0, rate: "0%" },
      { label: "Top referrer", value: "imasdk.googleapis.com (50)" },
      { label: "Google", value: 22 },
      { label: "LinkedIn", value: 7 },
      { label: "Geography", value: "77% US" },
      { label: "Device", value: "80% desktop" },
    ],
    notes: "Traffic growing (+464%) but zero conversions. 'Talk to Sales' CTA needs to change.",
  },
  {
    id: "scott-blast-1",
    name: "Scott — TIMA Clients #1",
    channel: "Email",
    mode: "Direct",
    motion: "sales",
    status: "active",
    dateRange: "Mar 2026",
    startDate: "2026-03-01",
    targeted: 250,
    reached: 150,
    replies: null,
    conversion: "0.4%",
    meetings: 1,
    pmfScore: 30,
    pmfNote: "1 qualified opp (Adelaide) from 250 emails. Low conversion rate but the opp that came through is real and in pipeline.",
    confidence: "medium",
    confidenceNote: "Email count and open rate are approximate. Adelaide opp is confirmed in Pipedrive.",
    details: [
      { label: "Emails sent", value: 250 },
      { label: "Opened", value: "~150", rate: "~60%" },
      { label: "Opps generated", value: 1 },
      { label: "Deal from campaign", value: "Adelaide" },
    ],
    notes: "Only Adelaide came from this campaign. Other pipeline deals (WEKA, Guardian Life, Consumable) came from organic/relationships. Instructure is an existing TIMA client.",
  },
  {
    id: "scott-blast-2",
    name: "Scott — TIMA Clients #2",
    channel: "Email",
    mode: "Direct",
    motion: "sales",
    status: "active",
    dateRange: "Mar 2026",
    startDate: "2026-03-15",
    targeted: 100,
    reached: null,
    replies: 0,
    conversion: "0%",
    meetings: 0,
    pmfScore: 0,
    pmfNote: "Second blast to same audience. Zero replies — message fatigue or wrong CTA.",
    confidence: "medium",
    confidenceNote: "Send count is known. Open/reply data approximate.",
    details: [
      { label: "Emails sent", value: 100 },
      { label: "Audience", value: "Same as Blast #1" },
      { label: "Replies", value: 0, rate: "0%" },
    ],
    notes: "Re-blast to same 100 people from Blast #1. Zero engagement — diminishing returns on same audience.",
  },
];

export const PROPOSED_EXPERIMENTS: ProposedExperiment[] = [
  // ===== ASAP PRIORITIES =====
  {
    id: "asap-1",
    name: "Homepage CTA — Schedule a Demo",
    channel: "accountcast.tv",
    motion: "product",
    hypothesis:
      "Replacing 'Talk to Sales' with 'Schedule a Demo' is lower friction — prospects know exactly what they're getting.",
    ctaTested: "Schedule a demo",
    durationWeeks: 2,
    successCriteria:
      "1%+ CTA click rate (vs. current 0%).",
    defaultScore: 0,
    startDate: "",
  },
  {
    id: "asap-2",
    name: "Homepage CTA — Download One-Pager",
    channel: "accountcast.tv",
    motion: "product",
    hypothesis:
      "A downloadable one-pager (gated with email) gives value first and captures leads without requiring a sales call.",
    ctaTested: "Download the one-pager (enter email)",
    durationWeeks: 2,
    successCriteria:
      "1%+ CTA click rate. Capture 10+ emails in 2 weeks.",
    defaultScore: 0,
    startDate: "",
  },
  {
    id: "asap-3",
    name: "Homepage CTA — Read the White Paper",
    channel: "accountcast.tv",
    motion: "product",
    hypothesis:
      "A white paper (gated with email) positions AccountCast as a thought leader and captures leads from research-oriented buyers.",
    ctaTested: "Read the white paper (enter email)",
    durationWeeks: 2,
    successCriteria:
      "1%+ CTA click rate. Capture 10+ emails in 2 weeks.",
    defaultScore: 0,
    startDate: "",
  },
  {
    id: "asap-4",
    name: "Homepage CTA — $2,000 Toward First Campaign",
    channel: "accountcast.tv",
    motion: "product",
    hypothesis:
      "Framing as 'we will give you $2,000' feels like a gift. Reduces risk and incentivizes trial.",
    ctaTested: "We will give you $2,000 toward your first campaign",
    durationWeeks: 2,
    successCriteria:
      "1%+ CTA click rate (vs. current 0%).",
    defaultScore: 0,
    startDate: "",
  },
  {
    id: "asap-5",
    name: "Homepage CTA — $2,000 Off First Campaign",
    channel: "accountcast.tv",
    motion: "product",
    hypothesis:
      "Framing as '$2,000 off' feels like a discount. Test whether 'give you' or 'off' converts better.",
    ctaTested: "$2,000 off your first campaign",
    durationWeeks: 2,
    successCriteria:
      "1%+ CTA click rate. Compare against 'toward' framing.",
    defaultScore: 0,
    startDate: "",
  },
  {
    id: "asap-6",
    name: "Britt — More Emails from 6sense/Clay",
    channel: "6sense / Clay",
    motion: "sales",
    hypothesis:
      "Expanding the lead list with 6sense/Clay intent data will give us more TAM accounts to target across all outbound campaigns.",
    ctaTested: "N/A — lead sourcing",
    durationWeeks: 1,
    successCriteria:
      "500+ new emails added to outbound lists from TAM accounts.",
    defaultScore: 0,
    startDate: "",
  },
  {
    id: "asap-7",
    name: "Danny — Re-upload Edtech List (TIMA)",
    channel: "Lemlist",
    motion: "sales",
    hypothesis:
      "Re-uploading the Edtech TAL to Lemlist will open a new audience vertical for AccountCast outbound.",
    ctaTested: "N/A — list upload",
    durationWeeks: 1,
    successCriteria:
      "List uploaded and campaign launched.",
    defaultScore: 0,
    startDate: "",
  },
  // ===== ADDITIONAL EXPERIMENTS =====
  {
    id: "prop-001",
    name: "Free Target Account List Offer",
    channel: "Lemlist",
    motion: "sales",
    hypothesis:
      "Offering a free TAL with intent data as a lead magnet will be more compelling than asking for a meeting — lower commitment, immediate value.",
    ctaTested: "Free Target Account List with intent data",
    durationWeeks: 2,
    successCriteria:
      "15%+ reply rate on Lemlist (vs. current 0%) and 50%+ of TAL recipients request a follow-up call.",
    defaultScore: 0,
    startDate: "",
  },
  {
    id: "prop-002",
    name: "CTV Creative Audit Offer",
    channel: "Lemlist",
    motion: "sales",
    hypothesis:
      "Brands already running CTV will engage with a free audit that shows gaps in their B2B targeting — positions AccountCast as the expert.",
    ctaTested: "Free CTV creative audit",
    durationWeeks: 2,
    successCriteria:
      "10%+ reply rate and 3+ audits delivered in 2 weeks.",
    defaultScore: 3,
    startDate: "",
  },
  {
    id: "prop-005",
    name: "Multithread — Dripify + Lemlist",
    channel: "Dripify + Lemlist",
    motion: "sales",
    hypothesis:
      "Reaching the same prospects on both LinkedIn and email will increase reply rates vs. single-channel outreach.",
    ctaTested: "Schedule a meeting",
    durationWeeks: 3,
    successCriteria:
      "Combined reply rate 15%+ (vs. ~7% LinkedIn-only and 0% email-only).",
    defaultScore: 2,
    startDate: "",
  },
  {
    id: "prop-004",
    name: "LinkedIn Ads — Awareness Campaign",
    channel: "LinkedIn",
    motion: "marketing",
    hypothesis:
      "Targeted LinkedIn ads to VP/Director Demand Gen will drive awareness and website visits, complementing the outbound motion.",
    ctaTested: "Schedule a demo",
    durationWeeks: 4,
    successCriteria:
      "CTR above 0.5%, at least 50 website visits from ads, 1+ demo request.",
    defaultScore: 1,
    startDate: "",
  },
  {
    id: "prop-006",
    name: "Loom Video Outbound",
    channel: "Lemlist",
    motion: "sales",
    hypothesis:
      "Personalized 60-second Loom videos showing what a CTV campaign would look like for the prospect's accounts will deliver the 'at last' moment visually — the way Scott does it 1:1.",
    ctaTested: "Schedule a demo",
    durationWeeks: 2,
    successCriteria:
      "20%+ video view rate, 10%+ reply rate, 1+ meeting booked.",
    defaultScore: 0,
    startDate: "",
  },
  {
    id: "prop-007",
    name: "Free Pilot — 'We Already Ran It'",
    channel: "Email",
    motion: "sales",
    hypothesis:
      "Run a tiny CTV campaign (1K impressions) against a prospect's target accounts without asking, then send results. Removes all friction — proves the product before they talk to us.",
    ctaTested: "See your campaign results",
    durationWeeks: 3,
    successCriteria:
      "3+ pilots delivered, 50%+ of pilot recipients take a follow-up call.",
    defaultScore: 0,
    startDate: "",
  },
  {
    id: "prop-008",
    name: "Homepage Video — 60 Second Demo",
    channel: "accountcast.tv",
    motion: "product",
    hypothesis:
      "Replace the text-heavy homepage with a 60-second video walkthrough of a real campaign. Let prospects SEE the magic moment instead of reading about it.",
    ctaTested: "Start your free campaign",
    durationWeeks: 2,
    successCriteria:
      "1%+ CTA click rate (vs. current 0%). 50%+ video completion rate.",
    defaultScore: 0,
    startDate: "",
  },
  {
    id: "prop-009",
    name: "Live 'B2B CTV in Action' Webinar",
    channel: "Events / Zoom",
    motion: "sales",
    hypothesis:
      "Scott's 1:1 pitch converts 100%. A monthly live demo webinar scales that to 1:many — invite the entire Dripify/Lemlist list to see it live.",
    ctaTested: "Register for live demo",
    durationWeeks: 4,
    successCriteria:
      "20+ registrations, 50%+ attendance, 3+ follow-up meetings from attendees.",
    defaultScore: 0,
    startDate: "",
  },
  {
    id: "prop-010",
    name: "Self-Serve Audience Builder",
    channel: "accountcast.tv",
    motion: "product",
    hypothesis:
      "Let anyone build a free Target Account List with intent data on the website — no login. They see the power of the data, then we ask for the meeting.",
    ctaTested: "Build your free TAL",
    durationWeeks: 4,
    successCriteria:
      "50+ TALs built in first month, 10%+ of builders request a follow-up.",
    defaultScore: 0,
    startDate: "",
  },
  {
    id: "prop-011",
    name: "Agency Partner Play",
    channel: "Partnerships",
    motion: "sales",
    hypothesis:
      "Find 3-5 media agencies already selling to Demand Gen leaders. Give them a white-label pitch and rev share. They have the trust, we have the product.",
    ctaTested: "Partner referral",
    durationWeeks: 4,
    successCriteria:
      "3+ agency partners signed, 1+ deal sourced through a partner in 60 days.",
    defaultScore: 0,
    startDate: "",
  },
];
